FROM eclipse-temurin:17-jre-jammy
WORKDIR /dejavu
COPY dejavu.jar /dejavu/dejavu.jar
RUN mkdir -p /sessions
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/dejavu/dejavu.jar"]
CMD ["--server", "--port", "8080", "--storage", "/sessions"]
